# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_number', models.UUIDField(default=uuid.uuid4)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('billing_address', models.TextField()),
                ('reference_id', models.BigIntegerField()),
                ('created_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
