# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-23 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.TextField(),
        ),
    ]
