# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsapp', '0002_auto_20180923_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
